import type { Metadata } from "next";
import {
  Fira_Code
} from "next/font/google";
import Buttoncard from "./_components/_button-card/ButtonCard";
import "./colors.css";
import "./globals.css";
import "./queries.css";

export const FiraCode = Fira_Code({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  variable: "--font-fira-code",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={FiraCode.variable}
      >
        {children}
        <Buttoncard />
      </body>
    </html>
  );
}
