import type { Metadata } from "next";
import { firaSansLight } from "@/_fonts/fonts";
import "./queries.css";
import "./colors.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${firaSansLight.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
